
# this will automatically resume previously-run MCMC chains with the same 
# `output` path that you've provided above
resume: True

theory:
  camb:
    extra_args:
      bbn_predictor: PArthENoPE_880.2_standard.dat
      NonLinear: NonLinear_both
      halofit_version: mead2016
      lens_potential_accuracy: 30
      lens_margin: 2050
      AccuracyBoost: 1.1
      lSampleBoost: 3.0
      lAccuracyBoost: 3.0
      DoLateRadTruncation: False
      num_massive_neutrinos: 1
      theta_H0_range:
      - 20
      - 100


params:
  logA:
    prior:
      min: 2
      max: 4
    ref:
      dist: norm
      loc: 3.05
      scale: 0.001
    proposal: 0.0003
    latex: \log(10^{10} A_\mathrm{s})
  As:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_\mathrm{s}
    derived: true
  ns:
    prior:
      min: 0.8
      max: 1.2
    ref:
      dist: norm
      loc: 0.965
      scale: 0.002
    proposal: 0.0002
    latex: n_\mathrm{s}
  theta_MC_100:
    prior:
      min: 0.5
      max: 10
    ref:
      dist: norm
      loc: 1.04092
      scale: 0.0004
    proposal: 0.00005
    latex: 100\theta_\mathrm{MC}
    drop: true
    renames: theta
  cosmomc_theta:
    value: 'lambda theta_MC_100: 1.e-2*theta_MC_100'
    derived: false
  H0:
    min: 20
    max: 100
    latex: H_0
  ombh2:
    prior:
      min: 0.005
      max: 0.1
    ref:
      dist: norm
      loc: 0.0224
      scale: 0.00005
    proposal: 7.8e-6
    latex: \Omega_\mathrm{b} h^2
  omch2:
    prior:
      min: 0.001
      max: 0.99
    ref:
      dist: norm
      loc: 0.12
      scale: 0.0005
    proposal: 2.2e-5
    latex: \Omega_\mathrm{c} h^2
  mnu:
    prior:
      min: 0
      max: 5
    ref:
      dist: norm
      loc: 0.06
      scale: 0.01
    proposal: 0.001
    latex: \sum m_\nu
  nnu:
    prior:
      min: 0.05
      max: 10
    ref:
      dist: norm
      loc: 3.046
      scale: 0.005
    proposal: 0.0013
    latex: N_\mathrm{eff}
  tau:
    prior:
      dist: norm
      loc: 0.054
      scale: 0.007
    ref:
      dist: norm
      loc: 0.054
      scale: 0.006
    proposal: 0.0002
    latex: \tau_\mathrm{reio}
  sigma8:
    latex: \sigma_8
  #HMCode_logT_AGN:
  #  prior:
  #    min: 7.6
  #    max: 8.0
  #  ref:
  #    dist: norm
  #    loc: 7.8
  #    scale: 0.03
  #  proposal: 0.006
  #  latex: \log_{10}(T_\mathrm{AGN}/\mathrm{K})

sampler:
  mcmc:
    Rminus1_stop: 0.01
    Rminus1_cl_stop: 0.2
    #covmat: hdlike/data/proposal_cov/from_chains/hd_delensed_desi_bao_lcdm_nnu_mnu.txt
    #covmat: hdlike/data/proposal_cov/from_chains/hd_delensed_lcdm_nnu_mnu_bao_hmcode2020_feedback.txt 

