# ----- Settings for the CMB-HD likelihood -----
# 
# These settings are used to automatically generate a Cobaya YAML file,
#  along with the `camb_cobaya_settings.yaml` file containing the CAMB and
#  Cobaya settings.
# See the Cobaya documentation for more information about the options in the 
#  YAML file.


# --- CMB-HD data ---
# Set `delensed: True` to use delensed CMB-HD data, otherwise set `delensed: False`.
# By default, *delensed* data is used.
delensed: True

# Set `baryonic_feedback: True` to run with a model including baryonic feedback
#  (i.e., use the 2020 version of HMCode with baryonic feedback effects and the 
#  power spectra generated for this model). 
# Otherwise set `baryonic_feedback: False` (or leave it blank) for a CDM-only model 
#  (i.e., use the 2016 version of HMCode and the corresponding power spectra).
# NOTE: To vary the baryonic feedback parameter (named `HMCode_logT_AGN` in CAMB), 
#  you must un-comment the `HMCode_logT_AGN` block in the `params` block of your
#  `camb_cobaya_settings.yaml` file. 
baryonic_feedback: False

# The maximum multipole of the lensed/delensed CMB TT,TE,EE,BB and lensing kk 
#  spectra, named `lmax` and `Lmax`, respectively, is 20100. This is used by 
#  default, i.e. if `lmax` or `Lmax` are not specified. We assume the minimum
#  multipole is fixed to `lmin = 30`.
# You may set a *lower* value of `lmax` or `Lmax` below, e.g. by 
#  setting `lmax: 5000`. This will truncate the spectra and covariance matrix.
#  However, note that lensing information from higher CMB multipoles will still
#  be included in the truncated lensing power spectrum, because all multipoles
#  in the range [30, 20100] were used to generate it. 
lmax: 
Lmax: 

# To use only lensed or delensed CMB TT, TE, EE, and BB power spectra and the
#  corresponding portion of the covariance matrix (i.e., to exclude the CMB 
#  lensing potential power spectrum and its covariance with the CMB spectra),
#  set `use_cmb_lensing_spectrum: False`. 
# By default (i.e., if `use_cmb_lensing_spectrum` is not specified), all primary 
#  CMB and CMB lensing data are used.
use_cmb_lensing_spectrum:

# To use only the CMB lensing power spectrum and covariance matrix (i.e., to
#  exclude the lensed or delensed CMB TT, TE, EE, and BB data), 
#  set `use_cmb_power_spectra: False`.
# By default (i.e., if `use_cmb_power_spectra` is not specified), all primary 
#  CMB and CMB lensing data are used.
use_cmb_power_spectra:

# To use a previous version of the CMB-HD mock data, set the `hd_data_version`
# to the version you would like to use. See the readme file in the `hdMockData`
# repository for more information. By default, the latest data will be used.
# If you would like to reproduce the results in MacInnis et. al. (2023),
# set `hd_data_version = v1.0`
hd_data_version:


# --- DESI BAO data ---
# Set `desi_bao: True` to use DESI BAO data, otherwise set `desi_bao: False`.
# By default, DESI BAO data is *NOT* included.
desi_bao: True


# --- MCMC ---
# To automatically set the proposal matrix (the `covmat` option under the `mcmc`
#  block of `camb_cobaya_settings.yaml`) if one exists, or the proposal widths
#  (the `proposal` option for each parameter in the `params` block) from a 
#  Fisher matrix, set `use_fisher_proposal_widths: True`. Otherwise, setting
#  `use_fisher_proposal_widths: False` (or leaving it blank) will not overwrite 
#  the values set in the `camb_cobaya_settings.yaml` file.
# Note that the Fisher matrices were calculated using the full covariance matrix
#  for the CMB-HD data (i.e. all multipoles and spectra included).
use_fisher_proposal_widths:


# --- Paths and file names ---
# Provide the full, absolute path to the directory in which you'd like to save
#  the Cobaya output, e.g. `output_dir: '/path/to/output_dir'. 
# NOTE: If this is left blank, the Cobaya output will be saved in whichever 
#       directory you call the `generate_cobaya_input_file.py` script from. 
# NOTE: If you're running MCMC chains, the output files may be large; choose the 
#       output directory wisely! For example, on NERSC, it is recommended to 
#       save  your chains in your `SCRATCH` directory.
output_dir: 
# Provide a name for the output files that will be saved in your `output_dir`,
#  e.g. `output_root: 'cmbhd_mcmc'`. Otherwise, if `output_root` is left blank, 
#  it will be automatically set based on the settings above.
output_root:

# Provide the full, absolute path to the directory in which you'd like to save
#  the generated Cobaya YAML file. Otherwise, if left blank, it will be saved
#  in whichever directory you call the `generate_cobaya_input_file.py` script from.
yaml_dir: 
# Provide a name for the YAML file, including the `.yaml` extension, that will be
#  generated by `generate_cobaya_input_file.py`. 
# If this is left blank, a name will be automatically generated based on the 
#  settings above (it will be the same as the automatic `output_root`, if applicable).
yaml_file_name: 
